### PR TITLE
Fix windows paths in pytest_flag

### LINKED ISSUE #25: Coverage arguments are broken on windows
I don't quite understand this but the coverage.xml path computation isn't working on windows.

We are going from this: https://github.com/DKISTDC/dkist/runs/5568366657?check_suite_focus=true#step:8:1 where the path looks ok to this: https://github.com/DKISTDC/dkist/runs/5568366657?check_suite_focus=true#step:8:15 where it isn't. Do we need an extra `\` here: https://github.com/OpenAstronomy/github-actions-workflows/blob/main/tools/tox_matrix.py#L117 or something?

### PR DESCRIPTION
**Pull request by ConorMacBride**
Fixes #25

### CODE REVIEW

**Comment by ConorMacBride** [comment]
Actions are not being triggered here?

**Comment by Cadair** [comment]
Oh it did eventually run: https://github.com/OpenAstronomy/github-actions-workflows/actions/runs/1993670911

**Comment by ConorMacBride** [comment]
It's just being slow today I think.

**Review by Cadair — APPROVED** [review]

**Comment by Cadair** [comment]
Seems to work! I shall merge and tag.

**Pull request merged**
