### PR TITLE
MNT: bump cibuildwheel to 2.20.0 (build cp313 wheels by default)

### PR DESCRIPTION
**Pull request by neutrinoceros**
Following the release of CPython 3.13.0rc1 (ABI stability).
xref https://github.com/pypa/cibuildwheel/releases/tag/v2.20.0

### CODE REVIEW

**Comment by Cadair** [comment]
@neutrinoceros is faster than dependabot 😁

**Review by Cadair — APPROVED** [review]

**Comment by Cadair** [comment]
I am on my phone, but does one of our test builds now build 3.13?

**Comment by neutrinoceros** [comment]
Doesn't look like it. Let me try to add it now.

**Review by ConorMacBride — APPROVED** [review]

**Comment by neutrinoceros** [comment]
@ConorMacBride is it possible to get this released soon ? if not, I note it's still possible to use it by replacing the version number with the hash of the merge commit.

**Comment by ConorMacBride** [comment]
@neutrinoceros That's released now :) https://github.com/OpenAstronomy/github-actions-workflows/releases/tag/v1.13.0

**Comment by neutrinoceros** [comment]
Ow, thanks a lot !

**Pull request merged**
