### PR TITLE
delete `set_env.py` after running in `tox.yml`

### LINKED ISSUE #115: pytest test discovery raises `GITHUB_ENV not set. Must be run inside GitHub Actions.`
when adding OpenAstronomy actions to the JWST pipeline (https://github.com/spacetelescope/jwst/pull/7498), the `pytest` test discovery step fails when encountering and executing `set_env.py`:
https://github.com/spacetelescope/jwst/actions/runs/4418621315/jobs/7745993137#step:10:241
```
_________________________ ERROR collecting set_env.py __________________________
set_env.py:9: in <module>
    raise ValueError("GITHUB_ENV not set. Must be run inside GitHub Actions.")
E   ValueError: GITHUB_ENV not set. Must be run inside GitHub Actions.
```

As far as I understand, `set_env.py` is created in the current working directory and run in `tox.yml`: https://github.com/OpenAstronomy/github-actions-workflows/blob/62c10bd5782a5a0e196a6c713c6db02d2392f234/.github/workflows/tox.yml#L174-L182

Would deleting `set_env.py` after running in the workflow solve this issue?

### PR DESCRIPTION
**Pull request by zacharyburnett**
resolves #115 

This attempts to solve the issue in #115 by ~~not writing `set_env.py` to a file~~ deleting `set_env.py` after running.

### CODE REVIEW

**Comment by zacharyburnett** [comment]
@ConorMacBride I apologize, I can't add reviewers to this PR. Do you think this is the correct approach to solving #115?

**Comment by zacharyburnett** [comment]
Attempting to execute the script as a string with `python -c $($SET_ENV_SCRIPT | base64 --decode)` did not work:
https://github.com/OpenAstronomy/github-actions-workflows/actions/runs/4429010028/jobs/7768901699#step:7:19
```
/home/runner/work/_temp/36262a4b-6471-4412-9bef-f6752a990797.sh: 2: aW1wb3J0IGpzb24KaW1wb3J0IG9zCmltcG9ydCBzeXMKCmltcG9ydCB5YW1sCgpHSVRIVUJfRU5WID0gb3MuZ2V0ZW52KCJHSVRIVUJfRU5WIikKaWYgR0lUSFVCX0VOViBpcyBOb25lOgogICAgcmFpc2UgVmFsdWVFcnJvcigiR0lUSFVCX0VOViBub3Qgc2V0LiBNdXN0IGJlIHJ1biBpbnNpZGUgR2l0SHViIEFjdGlvbnMuIikKCkRFTElNSVRFUiA9ICJFT0YiCgoKZGVmIHNldF9lbnYoZW52KToKCiAgICBlbnYgPSB5YW1sLmxvYWQoZW52LCBMb2FkZXI9eWFtbC5CYXNlTG9hZGVyKQogICAgcHJpbnQoanNvbi5kdW1wcyhlbnYsIGluZGVudD0yKSkKCiAgICBpZiBub3QgaXNpbnN0YW5jZShlbnYsIGRpY3QpOgogICAgICAgIHRpdGxlID0gImBlbnZgIG11c3QgYmUgbWFwcGluZyIKICAgICAgICBtZXNzYWdlID0gZiJgZW52YCBtdXN0IGJlIG1hcHBpbmcgb2YgZW52IHZhcmlhYmxlcyB0byB2YWx1ZXMsIGdvdCB0eXBlIHt0eXBlKGVudil9IgogICAgICAgIHByaW50KGYiOjplcnJvciB0aXRsZT17dGl0bGV9Ojp7bWVzc2FnZX0iKQogICAgICAgIGV4aXQoMSkKCiAgICBmb3IgaywgdiBpbiBlbnYuaXRlbXMoKToKCiAgICAgICAgaWYgbm90IGlzaW5zdGFuY2Uodiwgc3RyKToKICAgICAgICAgICAgdGl0bGUgPSAiYGVudmAgdmFsdWVzIG11c3QgYmUgc3RyaW5ncyIKICAgICAgICAgICAgbWVzc2FnZSA9IGYiYGVudmAgdmFsdWVzIG11c3QgYmUgc3RyaW5ncywgYnV0IHZhbHVlIG9mIHtrfSBoYXMgdHlwZSB7dHlwZSh2KX0iCiAgICAgICAgICAgIHByaW50KGYiOjplcnJvciB0aXRsZT17dGl0bGV9Ojp7bWVzc2FnZX0iKQogICAgICAgICAgICBleGl0KDEpCgogICAgICAgIHYgPSB2LnNwbGl0KCJcbiIpCgogICAgICAgIHdpdGggb3BlbihHSVRIVUJfRU5WLCAiYSIpIGFzIGY6CiAgICAgICAgICAgIGlmIGxlbih2KSA9PSAxOgogICAgICAgICAgICAgICAgZi53cml0ZShmIntrfT17dlswXX1cbiIpCiAgICAgICAgICAgIGVsc2U6CiAgICAgICAgICAgICAgICBmb3IgbGluZSBpbiB2OgogICAgICAgICAgICAgICAgICAgIGFzc2VydCBsaW5lLnN0cmlwKCkgIT0gREVMSU1JVEVSCiAgICAgICAgICAgICAgICBmLndyaXRlKGYie2t9PDx7REVMSU1JVEVSfVxuIikKICAgICAgICAgICAgICAgIGZvciBsaW5lIGluIHY6CiAgICAgICAgICAgICAgICAgICAgZi53cml0ZShmIntsaW5lfVxuIikKICAgICAgICAgICAgICAgIGYud3JpdGUoZiJ7REVMSU1JVEVSfVxuIikKCiAgICAgICAgcHJpbnQoZiJ7a30gd3JpdHRlbiB0byBHSVRIVUJfRU5WIikKCgppZiBfX25hbWVfXyA9PSAiX19tYWluX18iOgogICAgc2V0X2VudihzeXMuYXJndlsxXSkK: File name too long
[19](https://github.com/OpenAstronomy/github-actions-workflows/actions/runs/4429010028/jobs/7768901699#step:7:20)
Argument expected for the -c option
[20](https://github.com/OpenAstronomy/github-actions-workflows/actions/runs/4429010028/jobs/7768901699#step:7:21)
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
[21](https://github.com/OpenAstronomy/github-actions-workflows/actions/runs/4429010028/jobs/7768901699#step:7:22)
Try `python -h' for more information.
```

**Review by ConorMacBride — APPROVED** [review]

**Comment by ConorMacBride** [comment]
Thanks @zacharyburnett! It's a good idea to clean up this script after it's used.

**Comment by zacharyburnett** [comment]
thanks! This seems to have solved the issue in the JWST tests - https://github.com/spacetelescope/jwst/actions/runs/4418621315/jobs/7769529427

**Pull request merged**
