### PR TITLE
Rename pypi_password to pypi_token

### PR DESCRIPTION
**Pull request by astrofrog**
As suggested on Matrix - I think we should probably make this change sooner rather than later to avoid breaking things?

### CODE REVIEW

**Review by ConorMacBride — APPROVED** [review]

**Comment by astrofrog** [comment]
@Cadair - do you know if PyPI repositories other than the main one accept tokens?

**Comment by Cadair** [comment]
Not a clue

**Comment by astrofrog** [comment]
Could we just have pypi_token and then if we need in future we cold add pypi_username and pypi_password for cases where tokens aren't possible, if that is needed?

**Comment by astrofrog** [comment]
Then we could just set the username to __token__ by default and then for the password we can use 'password' if the username is not __token__ and otherwise pypi_token?

**Comment by ConorMacBride** [comment]
That would be possible, although unlike Azure, GitHub Actions doesn't seem to have a `coalesce(pypi_password, pypi_token)` function so might take a bit of work. Easiest option might be a separate upload action depending on if password or token is set.

**Comment by astrofrog** [comment]
Ok sounds good - I do think for the default case, token makes more sense (as the fact that the token is set as the password is kind of an implementation detail)

**Comment by astrofrog** [comment]
Ok sounds good - let's merge :)

**Pull request merged**
