### PR TITLE
Allow env vars to be passed to tox workflow

### PR DESCRIPTION
**Pull request by ConorMacBride**
Similar to #56 but extended to the tox workflow.

### CODE REVIEW

**Comment by pllim** [comment]
Is there a reason why this isn't merged? Could use this for https://github.com/astropy/astropy/pull/14401 or https://github.com/astropy/astropy/issues/14161

**Comment by ConorMacBride** [comment]
Glad it can be of use! Was just waiting for some reviews before committing to the API. The publishing workflows call the input `env` but I called it `setenv` in this PR so it isn't confused with the existing `envs` input in the tox workflow.

**Comment by pllim** [comment]
As long as that distinction is clearly documented, I am neutral on the name. Thanks!

**Comment by pllim** [comment]
Thanks for merging! Any plans to do a release so we can pick this up downstream under `v1`?

**Comment by ConorMacBride** [comment]
Yeah, could do. I think there's been quite a few features added. I'll do a release later today.

**Pull request merged**
