### PR TITLE
Set up initial publishing workflow

### PR DESCRIPTION
**Pull request by astrofrog**
A work in progress to add a re-usable workflow for building and publishing Python packages

@ConorMacBride - since you have worked a lot on the Azure templates recently, are you interested in also helping out here as a maintainer, as well as for the https://github.com/OpenAstronomy/action-build-sdist-and-wheel action?

Things still to do:

* [ ] Add the PyPA publish action
* [ ] Add documentation
* [ ] Check Azure templates for missing features
* [ ] Figure out how to pass cibuildwheel options, such as which builds to do etc.

One thing that is a bit clunky is the distinction between pure Python wheels and platform-depdendent wheels - it might be cleaner if we make those two separate workflow files?

### CODE REVIEW

**Comment by astrofrog** [comment]
I have to take a break from this for a bit, so happy for someone else to push commits here!

**Comment by ConorMacBride** [comment]
Hi @astrofrog, yes, I'm happy to help with maintaining the GitHub Actions repos also. Thanks! Your work on this looks brilliant. I'll have time over the weekend to hopefully have it ready for use.

**Review by ConorMacBride — APPROVED** [review]
This should work as-is for testing that wheels can be built correctly. So should we just merge this and add to it with additional PRs? Hopefully merging will also make the CI start running.

**Comment by astrofrog** [comment]
Yes let's just merge!

**Pull request merged**
